name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install dependencies for Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libxss1 \
          libappindicator3-1 \
          libindicator3-7 \
          fonts-liberation \
          libnspr4 \
          libnss3 \
          lsb-release \
          xdg-utils \
          wget

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install ChromeDriver
      run: |
        # Get the latest stable ChromeDriver version number
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        
        # Download ChromeDriver
        wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        
        # Unzip ChromeDriver
        unzip chromedriver_linux64.zip
        
        # Remove existing chromedriver and move the new one
        sudo rm -f /usr/bin/chromedriver
        sudo mv chromedriver /usr/bin/chromedriver
        rm chromedriver_linux64.zip

    - name: Print Google Chrome version
      run: google-chrome --version

    - name: Run Tests in Headless Mode
      run: mvn clean test -Dwebdriver.chrome.driver=/usr/bin/chromedriver -Dchrome.options="--headless --no-sandbox --disable-gpu"
      working-directory: automation
      env:
        CHROME_BIN: /usr/bin/google-chrome
